on:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Create a text file
              run: |
                  echo "The time is $(date -u)" > time.txt

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: time-artifact # optional, default is the name of the workflow job
                  path: time.txt
                  if-no-files-found: error # optional, default is warn
                  retention-days: 1 # optional, maximum retention period is 90 days
                  
    print:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download the Build Artifact
              uses: actions/download-artifact@v3
              with:
                  name: time-artifact
            - name: Print the contents of the text file
              run: cat time.txt