name: Time artifact
on:
  push:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create a text file
        run: |
          echo "The time is $(time -u)" > my-artifact.txt

      - name: Upload the text file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: my-artifact.txt
          if-no-files-found: error # optional, default is warn
          retention-days: 1 # optional, maximum 90 days
        
  print:
      runs-on: ubuntu-latest
      needs: create
      steps:
          - name: Download the time artifact
            uses: actions/download-artifact@v3
            with:
                name: time-artifact
                path: time.txt
          - name: Print the contents of the text file
            run: cat time.txt


