name: Time artifact
on:
  push:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create a text file
        run: |
          echo "The time is $(date -u)" > time.txt

      - name: Upload the text file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: time-artifact # optional, default is artifact
          path: time.txt
          if-no-files-found: error # optional, default is warn
          retention-days: 1 # optional, maximum 90 days
        
  print:
      runs-on: ubuntu-latest
      needs: create
      steps:
          - name: Download the artifact created by the create job
            uses: actions/download-artifact@v3
            id: download-artifact
            with:
                name: time-artifact
                path: ~/time.txt
                
          - name: The download path
            run: echo ${{ steps.download-artifact.outputs.download-path }}

          - name: Download all artifacts
            uses: actions/download-artifact@v3
            with:
                path: ~/all-artifacts 

          - name: The download path for all artifacts
            run: echo ${{ steps.download-artifact.outputs.download-path }}

