name: Time artifact
on:
  push:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Some previous step
        run: ech "I am going to fail"
        
      - name: Upload on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: failure-artifact
          path: **/*.log
    
